### ISSUE TITLE
Can't pass "force" as a parameter to clean task

### ISSUE THREAD

**Issue by kentmw** [vecnatechnologies/quick-sip#9]
Somewhat a lower priority, but if the dist folder is outside the directory the gulp file is, then clean won't work without force option

**Comment by mandragorn** [comment]
@kentmw  was this fixed by https://github.com/vecnatechnologies/quick-sip/pull/11 ?

**Comment by kentmw** [comment]
https://github.com/vecnatechnologies/quick-sip/blob/master/tasks/clean.js#L10
still doesn't let you pass any options (including force) you want.

**Comment by mandragorn** [comment]
Fixed by #15
